# Generated by Django 2.2.4 on 2019-08-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djang_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='seats',
            name='name',
            field=models.CharField(max_length=3),
        ),
        migrations.AddField(
            model_name='seats',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djang_models.Passenger'),
            preserve_default=False,
        ),
    ]
