# Generated by Django 2.2.4 on 2019-08-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djang_models', '0002_passenger_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='seatnumber',
        ),
    ]
